services:
  mysql:
    image: mysql:9.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
